name: optimize-images

on:
  push:
    # 只有改动 static/image/ 下的 jpg/png 才触发
    paths:
      - "static/image/**.jpg"
      - "static/image/**.png"

jobs:
  webp:
    runs-on: ubuntu-latest

    steps:
      # ① 拉代码
      - uses: actions/checkout@v4

      # ② 安装 squoosh/cli（一次性缓存）
      - run: npm i -g @squoosh/cli

      # ③ 执行批量压缩＋转码：1600px + q80 WebP
      - name: squash to webp
        run: |
          squoosh-cli \
            --webp '{"quality":80}' \
            --resize '{"maxWidth":1600}' \
            "static/image/**/*.{jpg,png}"

      # ④ 提交优化后的文件回仓库（如果有变化）
      - name: commit optimized images
        run: |
          git config user.name  "img-bot"
          git config user.email "img-bot@users.noreply.github.com"
          git add -u static/image/
          git diff --cached --quiet || \
            git commit -m "ci: optimize images"
      - run: git push
