name: auto-webp

permissions:          # ← 新增
  contents: write     # ← 新增，给 GITHUB_TOKEN 写入 repo 的权力
  
on:                       # 任何推送都会触发，也可手点 Run workflow
  push:
    branches: [ main ]    # 改成你 Pages 用的分支
  workflow_dispatch:      # 需要时手动触发

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    # 1. 拉代码
    - uses: actions/checkout@v4

    # 2. 安装 WebP 工具
    - run: sudo apt-get update && sudo apt-get install -y webp

    # 3. 把 static/image 里的 jpg/png 全部转成 webp
    - name: Generate .webp
      run: |
        find static/image -type f \( -iname '*.jpg' -o -iname '*.png' \) \
          -exec sh -c '
            for img; do
              out="${img%.*}.webp"
              # 只在 .webp 不存在时生成，避免反复重压
              [ -e "$out" ] || cwebp -quiet -q 80 "$img" -o "$out"
            done
          ' sh {} +

    # 4. 把 HTML 里的 <img> 包上 <picture> —— 保留 data-full 等属性不动
    - name: Inject <picture> wrappers
      run: |
        for page in $(git ls-files '*.html'); do
          perl -0777 -pi -e '
            s{
              (<img \s+                               # 起始 <img
               [^>]*? \b src="([^"]+\.(?:jpe?g|png))" # 抓 src 路径
               [^>]*?>)                               # 直到 >
            }{
              my $img = $1;            # 整个 <img …>
              my $src = $2;            # static/image/foo.jpg
              my $webp = $src; $webp =~ s/\.(?:jpe?g|png)$/\.webp/i;
              qq|<picture><source srcset="$webp" type="image/webp">$img</picture>|;
            }egix;
          ' "$page"
        done

    # 5. 只有改动时才提交，防止死循环
    - name: Commit & push
      run: |
        git config user.name  Auto Bot
        git config user.email noreply@example.com
        if ! git diff --quiet; then
          git add .
          git commit -m "auto: webp + picture wrapper"
          git push
        fi
